university:
  name: binghamton

logging:
  level:
    sql: trace
    org:
      springframework:
        jdbc:
          datasource: trace
server:
  shutdown: graceful

spring:
  datasource:
    name: ACAD111
    port: ${DB_PORT}
    type: oracle.jdbc.pool.OracleDataSource
    host: ${DB_HOST}
    driver-url: jdbc:oracle:thin
    url: ${spring.datasource.driver-url}:@${spring.datasource.host}:${spring.datasource.port}:${spring.datasource.name}
    username: ${DB_USER}
    password: ${DB_PASS}
  sql:
    init:
      mode: always
      schema-locations: "classpath*:sql/schema.sql"
      data-locations: "classpath*:sql/data.sql"
      separator: "^"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  lifecycle:
    timeout-per-shutdown-phase: 30s
